//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMasInfo.Negocio.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteUbicacion
    {
        public int Id { get; set; }
        public long IdPaciente { get; set; }
        public int IdUbicacion { get; set; }
        public Nullable<System.DateTime> FchIngreso { get; set; }
        public string UsrIngreso { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
